### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by shashankpsingh** [venshine/WheelView#41]
Hey got this error 👎
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at android.os.Handler.removeMessages(Handler.java:648)
       at android.view.Choreographer.removeCallbacksInternal(Choreographer.java:414)
       at android.view.Choreographer.removeCallbacks(Choreographer.java:402)
       at android.view.View.removeCallbacks(View.java:13183)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4751)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5020)
       at android.widget.AbsListView.smoothScrollBy(AbsListView.java:5001)
       at com.ela.android.utilities.wheelview.widget.WheelView$4.onScrollStateChanged(Unknown Source)
       at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4599)
       at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4754)
       at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4851)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
       at android.view.Choreographer.doCallbacks(Choreographer.java:676)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5885)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by Hanif-abuvani** [comment]
Same here in All HTC device

**Comment by HDHunter** [comment]
Same problem . in HTC device of Android 8.0 .

**Comment by gj009351** [comment]
Same here in All HTC device

**Comment by 1024-1024** [comment]
Same here in All HTC device
